package barrelenv

import (
	"fmt"
	"strings"

	"github.com/rickchristie/govner/cooper/internal/config"
)

var protectedRuntimeStaticNames = []string{
	"HTTP_PROXY",
	"HTTPS_PROXY",
	"NO_PROXY",
	"http_proxy",
	"https_proxy",
	"no_proxy",
	"ALL_PROXY",
	"all_proxy",
	"PATH",
	"HOME",
	"USER",
	"LOGNAME",
	"SHELL",
	"TZ",
	"TERM",
	"COLORTERM",
	"TERM_PROGRAM",
	"TERM_PROGRAM_VERSION",
	"COLORFGBG",
	"LC_TERMINAL",
	"LC_TERMINAL_VERSION",
	"TERM_SESSION_ID",
	"ITERM_PROFILE",
	"ITERM_SESSION_ID",
	"VTE_VERSION",
	"KONSOLE_VERSION",
	"KONSOLE_PROFILE_NAME",
	"WT_SESSION",
	"WT_PROFILE_ID",
	"KITTY_WINDOW_ID",
	"WEZTERM_PANE",
	"TERMINAL_EMULATOR",
	"DOMTERM",
	"TERMINOLOGY",
	"NO_COLOR",
	"FORCE_COLOR",
	"FORCE_HYPERLINK",
	"CLICOLOR",
	"CLICOLOR_FORCE",
	"NODE_DISABLE_COLORS",
	"DISPLAY",
	"XAUTHORITY",
	"PLAYWRIGHT_BROWSERS_PATH",
	"NODE_EXTRA_CA_CERTS",
	"NPM_CONFIG_PREFIX",
	"GOPATH",
	"GOMODCACHE",
	"GOCACHE",
	"COOPER_PROXY_HOST",
	"COOPER_INTERNAL_NETWORK",
	"COOPER_CLIPBOARD_DISPLAY",
	"COOPER_CLIPBOARD_XAUTHORITY",
	"COOPER_CLIPBOARD_ENABLED",
	"COOPER_CLIPBOARD_BRIDGE_URL",
	"COOPER_CLIPBOARD_TOKEN_FILE",
	"COOPER_CLIPBOARD_SHIMS",
	"COOPER_CLI_TOOL",
	"COOPER_CLI_AUTO_APPROVE",
	"COOPER_CLIPBOARD_MODE",
}

// RenderUserEnvFile renders literal shell exports for user-provided barrel envs.
func RenderUserEnvFile(vars []config.BarrelEnvVar) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated by cooper cli. User barrel env vars only.\n")
	for _, variable := range vars {
		name := strings.TrimSpace(variable.Name)
		if name == "" {
			return nil, fmt.Errorf("env name is required")
		}
		b.WriteString("export ")
		b.WriteString(name)
		b.WriteString("=")
		b.WriteString(shellSingleQuote(variable.Value))
		b.WriteString("\n")
	}
	return []byte(b.String()), nil
}

// ProtectedRuntimeEnvNames returns the stable runtime env restore list with any
// dynamic token or IDE names appended once. Callers pass the names resolved for
// the current tool so runtime restore stays aligned with auth.ResolveTokens
// instead of freezing a token list in this package.
func ProtectedRuntimeEnvNames(extra []string) []string {
	seen := make(map[string]struct{}, len(protectedRuntimeStaticNames)+len(extra))
	names := make([]string, 0, len(protectedRuntimeStaticNames)+len(extra))
	appendUnique := func(name string) {
		if name == "" {
			return
		}
		if _, ok := seen[name]; ok {
			return
		}
		seen[name] = struct{}{}
		names = append(names, name)
	}
	for _, name := range protectedRuntimeStaticNames {
		appendUnique(name)
	}
	for _, name := range extra {
		appendUnique(strings.TrimSpace(name))
	}
	return names
}

// BuildExecWrapperCommand builds the exact argv passed to docker exec so user
// env can be loaded without allowing protected Cooper env to be overridden.
// The outer wrapper intentionally stays `bash -c` (non-login) while targetCmd
// remains the final `bash -l` or `bash -c` invocation. That avoids sourcing
// shell startup files twice and keeps one-shot command text out of the wrapper
// script body so host-side quoting is not reintroduced.
func BuildExecWrapperCommand(userEnvFile string, protectedNames []string, targetCmd []string) ([]string, error) {
	if len(targetCmd) == 0 {
		return nil, fmt.Errorf("target command is required")
	}
	wrapperScript, err := buildWrapperScript(protectedNames)
	if err != nil {
		return nil, err
	}
	argv := []string{"bash", "-c", wrapperScript, "cooper-env-wrapper", userEnvFile}
	argv = append(argv, targetCmd...)
	return argv, nil
}

// buildWrapperScript snapshots protected vars before sourcing the user env
// file, then restores them afterward while preserving whether each name was
// originally set or unset in the wrapper process.
func buildWrapperScript(protectedNames []string) (string, error) {
	protectedNames = dedupeNames(protectedNames)

	var b strings.Builder
	b.WriteString("set -euo pipefail\n\n")
	b.WriteString("user_env_file=\"$1\"\n")
	b.WriteString("shift\n\n")

	for _, name := range protectedNames {
		if name == "" {
			continue
		}
		if !isShellIdentifier(name) {
			return "", fmt.Errorf("protected env name %q is not a valid shell identifier", name)
		}
		fmt.Fprintf(&b, "__cooper_has_%s=0\n", name)
		fmt.Fprintf(&b, "if [[ ${%s+x} ]]; then\n", name)
		fmt.Fprintf(&b, "  __cooper_has_%s=1\n", name)
		fmt.Fprintf(&b, "  __cooper_val_%s=\"$%s\"\n", name, name)
		b.WriteString("fi\n\n")
	}

	b.WriteString("if [[ -n \"$user_env_file\" && -f \"$user_env_file\" ]]; then\n")
	b.WriteString("  # shellcheck source=/dev/null\n")
	b.WriteString("  . \"$user_env_file\"\n")
	b.WriteString("fi\n\n")

	for _, name := range protectedNames {
		if name == "" {
			continue
		}
		fmt.Fprintf(&b, "if [[ $__cooper_has_%s -eq 1 ]]; then\n", name)
		fmt.Fprintf(&b, "  export %s=\"$__cooper_val_%s\"\n", name, name)
		b.WriteString("else\n")
		fmt.Fprintf(&b, "  unset %s\n", name)
		b.WriteString("fi\n\n")
	}

	b.WriteString("exec \"$@\"\n")
	return b.String(), nil
}

func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

func dedupeNames(names []string) []string {
	seen := make(map[string]struct{}, len(names))
	result := make([]string, 0, len(names))
	for _, name := range names {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		result = append(result, name)
	}
	return result
}

func isShellIdentifier(name string) bool {
	if name == "" {
		return false
	}
	if name[0] != '_' && (name[0] < 'A' || name[0] > 'Z') && (name[0] < 'a' || name[0] > 'z') {
		return false
	}
	for i := 1; i < len(name); i++ {
		ch := name[i]
		if ch == '_' {
			continue
		}
		if ch >= 'A' && ch <= 'Z' {
			continue
		}
		if ch >= 'a' && ch <= 'z' {
			continue
		}
		if ch >= '0' && ch <= '9' {
			continue
		}
		return false
	}
	return true
}
