package clipboard

import "fmt"

// cooperClipFetchFunc is the shared binary-safe fetch helper used by all shims.
// It reads the bearer token from $COOPER_CLIPBOARD_TOKEN_FILE (never from env
// vars or CLI args), downloads the image to a tmpfile via curl, and cats it to
// stdout. The mktemp+curl+cat pattern avoids piping binary data through shell
// variables, which would corrupt NUL bytes.
const cooperClipFetchFunc = `
_cooper_clip_fetch() {
    local token
    token=$(cat "${COOPER_CLIPBOARD_TOKEN_FILE}" 2>/dev/null) || return 1
    [ -n "$token" ] || return 1
    local bridge="${COOPER_CLIPBOARD_BRIDGE_URL}"
    [ -n "$bridge" ] || return 1
    local tmpfile
    tmpfile=$(mktemp) || return 1
    if curl -fsS --max-time 5 \
        -o "$tmpfile" \
        -H "Authorization: Bearer ${token}" \
        "${bridge}/clipboard/image"; then
        if [ ! -s "$tmpfile" ]; then
            rm -f "$tmpfile"
            return 1
        fi
        cat "$tmpfile"
        rm -f "$tmpfile"
        return 0
    fi
    rm -f "$tmpfile"
    return 1
}

_cooper_clip_post_text_file() {
    local text_file="$1"
    [ -f "$text_file" ] || return 1
    local token
    token=$(cat "${COOPER_CLIPBOARD_TOKEN_FILE}" 2>/dev/null) || return 1
    [ -n "$token" ] || return 1
    local bridge="${COOPER_CLIPBOARD_BRIDGE_URL}"
    [ -n "$bridge" ] || return 1
    curl -fsS --max-time 5 \
        -X POST \
        -H "Authorization: Bearer ${token}" \
        -H "Content-Type: text/plain; charset=utf-8" \
        --data-binary "@${text_file}" \
        "${bridge}/clipboard/text" >/dev/null
}
`

// XclipShim returns a complete bash script that intercepts clipboard read
// patterns used by AI CLI tools (e.g., Claude Code, OpenCode) and serves
// staged images from the Cooper clipboard bridge. All other invocations
// fall through to the real xclip binary.
//
// Intercepted patterns:
//   - xclip -selection clipboard -t TARGETS -o  → synthetic TARGETS response
//   - xclip -selection clipboard -t image/* -o  → fetch from bridge
func XclipShim(realXclipPath string) string {
	return fmt.Sprintf(`#!/bin/bash
# Cooper clipboard shim for xclip
# Intercepts clipboard image reads and serves staged images from the bridge.
# All other invocations are forwarded to the real xclip binary.
# DO NOT EDIT - Generated by cooper.

REAL_BINARY="%s"

# Guard: if clipboard bridge is not enabled, always use real binary.
if [ "${COOPER_CLIPBOARD_ENABLED}" != "1" ]; then
    exec "$REAL_BINARY" "$@"
fi
%s
_cooper_xclip_has_output_flag() {
    local arg
    for arg in "$@"; do
        case "$arg" in
            -o|-out|--output)
                return 0
                ;;
        esac
    done
    return 1
}

_cooper_xclip_selection_is_clipboard() {
    local arg
    while [ $# -gt 0 ]; do
        arg="$1"
        case "$arg" in
            -selection|-sel)
                shift
                case "$1" in
                    clipboard|clip|c)
                        return 0
                        ;;
                esac
                ;;
            -selection=clipboard|-selection=clip|-selection=c|-sel=clipboard|-sel=clip|-sel=c)
                return 0
                ;;
        esac
        shift
    done
    return 1
}

_cooper_xclip_is_clipboard_write() {
    _cooper_xclip_has_output_flag "$@" && return 1
    _cooper_xclip_selection_is_clipboard "$@"
}

_cooper_xclip_forward_text_write() {
    local tmpfile
    tmpfile=$(mktemp) || return 1
    if ! cat > "$tmpfile"; then
        rm -f "$tmpfile"
        return 1
    fi
    if ! _cooper_clip_post_text_file "$tmpfile"; then
        rm -f "$tmpfile"
        return 1
    fi
    "$REAL_BINARY" "$@" < "$tmpfile" >/dev/null 2>&1 || true
    rm -f "$tmpfile"
    return 0
}

# Normalize arguments into a single string for matching.
args="$*"

if _cooper_xclip_is_clipboard_write "$@"; then
    if _cooper_xclip_forward_text_write "$@"; then
        exit 0
    fi
    exit 1
fi

# Pattern: xclip -selection clipboard -t TARGETS -o
# AI tools call this to discover available clipboard types.
# Only advertise image/png if the bridge actually has a staged image.
case "$args" in
    *-selection*clipboard*-t*TARGETS*-o*|-selection*clipboard*-o*-t*TARGETS*)
        _clip_token=$(cat "${COOPER_CLIPBOARD_TOKEN_FILE}" 2>/dev/null) || true
        _clip_bridge="${COOPER_CLIPBOARD_BRIDGE_URL}"
        if [ -n "$_clip_token" ] && [ -n "$_clip_bridge" ]; then
            _type_resp=$(curl -fsS --max-time 2 \
                -H "Authorization: Bearer ${_clip_token}" \
                "${_clip_bridge}/clipboard/type" 2>/dev/null) || true
            if echo "$_type_resp" | grep -q '"staged"'; then
                printf 'TARGETS\nimage/png\n'
                exit 0
            fi
        fi
        exec "$REAL_BINARY" "$@"
        ;;
esac

# Pattern: xclip -selection clipboard -t image/<type> -o
# AI tools call this to read the actual image data.
case "$args" in
    *-selection*clipboard*-t*image/*-o*|-selection*clipboard*-o*-t*image/*)
        if _cooper_clip_fetch; then
            exit 0
        fi
        # Fetch failed — fall through to real binary.
        exec "$REAL_BINARY" "$@"
        ;;
esac

# Everything else: pass through to real xclip.
exec "$REAL_BINARY" "$@"
`, realXclipPath, cooperClipFetchFunc)
}

// XselShim returns a complete bash script that acts as a passthrough to the
// real xsel binary. xsel does not support target selection natively, so AI
// tools primarily use xclip for image reads. This shim exists as a safety
// net and simply forwards all calls to the real binary.
func XselShim(realXselPath string) string {
	return fmt.Sprintf(`#!/bin/bash
# Cooper clipboard shim for xsel
# xsel does not support target selection (image types), so AI tools use xclip
# for image reads. This shim is a safety net — it passes all calls through
# to the real xsel binary.
# DO NOT EDIT - Generated by cooper.

REAL_BINARY="%s"

# Guard: if clipboard bridge is not enabled, always use real binary.
if [ "${COOPER_CLIPBOARD_ENABLED}" != "1" ]; then
    exec "$REAL_BINARY" "$@"
fi
%s
_cooper_xsel_is_clipboard_write() {
    local arg short_flags
    local has_clipboard=0
    local has_output=0
    local has_input=0

    for arg in "$@"; do
        case "$arg" in
            --clipboard)
                has_clipboard=1
                ;;
            --output)
                has_output=1
                ;;
            --input)
                has_input=1
                ;;
            -*)
                short_flags="${arg#-}"
                case "$short_flags" in
                    *b*) has_clipboard=1 ;;
                esac
                case "$short_flags" in
                    *o*) has_output=1 ;;
                esac
                case "$short_flags" in
                    *i*) has_input=1 ;;
                esac
                ;;
        esac
    done

    [ "$has_clipboard" = "1" ] || return 1
    [ "$has_output" = "0" ] || return 1
    [ "$has_input" = "1" ] || return 0
    return 0
}

_cooper_xsel_forward_text_write() {
    local tmpfile
    tmpfile=$(mktemp) || return 1
    if ! cat > "$tmpfile"; then
        rm -f "$tmpfile"
        return 1
    fi
    if ! _cooper_clip_post_text_file "$tmpfile"; then
        rm -f "$tmpfile"
        return 1
    fi
    /usr/bin/xclip -selection clipboard < "$tmpfile" >/dev/null 2>&1 || true
    rm -f "$tmpfile"
    return 0
}

if _cooper_xsel_is_clipboard_write "$@"; then
    if _cooper_xsel_forward_text_write "$@"; then
        exit 0
    fi
    exit 1
fi

# Pattern: xsel --clipboard --output (simple clipboard read)
# If an image is staged, return it; otherwise fall back to real xsel.
case "$*" in
    *--clipboard*--output*|*--clipboard*-o|*-b*--output*|*-b*-o)
        if _cooper_clip_fetch 2>/dev/null; then
            exit 0
        fi
        # No staged image or fetch failed — fall through to real binary.
        exec "$REAL_BINARY" "$@"
        ;;
esac

# Everything else: pass through to real xsel.
exec "$REAL_BINARY" "$@"
`, realXselPath, cooperClipFetchFunc)
}

// WlPasteShim returns a complete bash script that intercepts clipboard read
// patterns used by AI CLI tools on Wayland and serves staged images from
// the Cooper clipboard bridge. All other invocations fall through to the
// real wl-paste binary.
//
// Intercepted patterns:
//   - wl-paste --list-types    → synthetic type list
//   - wl-paste --type image/*  → fetch from bridge
func WlPasteShim(realWlPastePath string) string {
	return fmt.Sprintf(`#!/bin/bash
# Cooper clipboard shim for wl-paste
# Intercepts clipboard image reads and serves staged images from the bridge.
# All other invocations are forwarded to the real wl-paste binary.
# DO NOT EDIT - Generated by cooper.

REAL_BINARY="%s"

# Guard: if clipboard bridge is not enabled, always use real binary.
if [ "${COOPER_CLIPBOARD_ENABLED}" != "1" ]; then
    exec "$REAL_BINARY" "$@"
fi
%s
# Normalize arguments into a single string for matching.
args="$*"

# Pattern: wl-paste --list-types
# AI tools call this to discover available clipboard types.
# Only advertise image/png if the bridge actually has a staged image.
case "$args" in
    *--list-types*)
        _clip_token=$(cat "${COOPER_CLIPBOARD_TOKEN_FILE}" 2>/dev/null) || true
        _clip_bridge="${COOPER_CLIPBOARD_BRIDGE_URL}"
        if [ -n "$_clip_token" ] && [ -n "$_clip_bridge" ]; then
            _type_resp=$(curl -fsS --max-time 2 \
                -H "Authorization: Bearer ${_clip_token}" \
                "${_clip_bridge}/clipboard/type" 2>/dev/null) || true
            if echo "$_type_resp" | grep -q '"staged"'; then
                printf 'image/png\n'
                exit 0
            fi
        fi
        exec "$REAL_BINARY" "$@"
        ;;
esac

# Pattern: wl-paste --type image/<type>
# AI tools call this to read the actual image data.
case "$args" in
    *--type*image/*)
        if _cooper_clip_fetch; then
            exit 0
        fi
        # Fetch failed — fall through to real binary.
        exec "$REAL_BINARY" "$@"
        ;;
esac

# Everything else: pass through to real wl-paste.
exec "$REAL_BINARY" "$@"
`, realWlPastePath, cooperClipFetchFunc)
}
